name: terraform-automation
on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-2"
  IMAGE_TAG: "latest"
  ECR_REPOSITORY: "tf-automation-repo"
  TASK_DEFINITON: task-definition.json
  TASK_DEFINITION_FAMILY: "app-td"
  CONTAINER_NAME: "app"
  SERVICE: "app-ecs-service"
  CLUSTER: "app-cluster"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon Ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build, tag and push the image to Amazon Ecr
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      
      - name: Apply terraform
        run: terraform init && terraform apply --auto-approve
        working-directory: terraform

      - name: Export task definition
        id: export-td
        env:
          TD_NAME: ${{ secrets.TASK_DEFINITON }}
          TD_FAMILY: ${{ secrets.TASK_DEFINITION_FAMILY}}
        run: |
          rm -rf $TD_NAME
          aws ecs describe-task-definition --task-definition $TD_FAMILY --query taskDefinition > $TD_NAME
  
      - name: Check exported Task Definition
        run: |
          ls

      - name: Update the image in the task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition/@v2
        with:
          task-definition: ${{ secrets.TASK_DEFINITON }}
          container-name: ${{ secrets.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}
      
      - name: Deploy task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ env.TASK_DEFINITON }}
          service: ${{ secrets.SERVICE}}
          cluster: ${{ secrets.CLUSTER}}
